CREATE TABLE IF NOT EXISTS public.extraction_sessions (
  id UUID PRIMARY KEY,
  extraction_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  query TEXT NOT NULL,
  location TEXT,
  source TEXT NOT NULL DEFAULT 'google_maps',
  search_type TEXT,
  api_provider TEXT,
  website_filter TEXT,
  requested_max_results INTEGER,
  leads_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'running',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.extraction_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own extraction sessions" ON public.extraction_sessions;
CREATE POLICY "Users can view own extraction sessions"
  ON public.extraction_sessions FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own extraction sessions" ON public.extraction_sessions;
CREATE POLICY "Users can insert own extraction sessions"
  ON public.extraction_sessions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own extraction sessions" ON public.extraction_sessions;
CREATE POLICY "Users can update own extraction sessions"
  ON public.extraction_sessions FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own extraction sessions" ON public.extraction_sessions;
CREATE POLICY "Users can delete own extraction sessions"
  ON public.extraction_sessions FOR DELETE
  USING (auth.uid() = user_id);

DROP TRIGGER IF EXISTS update_extraction_sessions_updated_at ON public.extraction_sessions;
CREATE TRIGGER update_extraction_sessions_updated_at
  BEFORE UPDATE ON public.extraction_sessions
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS extraction_session_id UUID
  REFERENCES public.extraction_sessions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS leads_extraction_session_id_idx
  ON public.leads (extraction_session_id);

CREATE INDEX IF NOT EXISTS extraction_sessions_user_created_idx
  ON public.extraction_sessions (user_id, created_at DESC);
